-- ============================================
-- DEPRECATED: legacy unified identity bootstrap
--
-- ไฟล์นี้เคยใช้กับแนวทาง LINE + Telegram แบบแยก identity schema
-- แต่ runtime ปัจจุบันของโปรเจกต์ใช้ schema หลักใน init-db.sql
-- ร่วมกับ migration ที่จำเป็นเท่านั้น
--
-- ห้ามใช้ไฟล์นี้สำหรับตั้งฐานข้อมูลใหม่ของระบบปัจจุบัน
-- ให้ใช้ลำดับดังนี้แทน:
--   1) init-db.sql
--   2) migrate-unified.sql
--   3) migrate-guess-cycle.sql
--   4) migrate-reward-claim-mode.sql
--   5) migrate-sold-out-round.sql
-- ============================================
